/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DeskHitbox.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";
import gsap from "gsap";
import { useUiStore } from "../../stores/uiStore";
import { useNavigate } from "react-router";

export default function Model(props) {
  let navigate = useNavigate();

  const { openPanel } = useUiStore();

  const basePath = process.env.PUBLIC_URL || '';

  const { nodes, materials } = useGLTF(`${basePath}/models/DeskHitbox.glb`);

  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff });

  const devWorkAnimRef = useRef();

  const animationPairs = {
    Dev_Work_Hitbox: {ref: devWorkAnimRef},
  };

  //Handle Hover 
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? .027 : 0,
      y: isHovering ? .027 : 0,
      z: isHovering ? .027 : 0,
      duration: 0.5
    })
  }


  return (
    <group {...props} dispose={null}>
      <mesh 
      geometry={nodes.DeskHitBox.geometry} 
      material={materials['Material.001']} 
      position={[2.243, 1.947, -2.128]} 
      scale={[2.206, 1.606, 1.502]} 
      visible={false}
      onPointerOver={()=> {
        onHover("Dev_Work_Hitbox", true);
        document.body.style.cursor = "pointer";
      }}
      onPointerOut={()=> {
        onHover("Dev_Work_Hitbox", false);
        document.body.style.cursor = "auto";
      }}
      onClick={()=> {
        openPanel("Dev_Work_Hitbox");
        navigate("/dev-work");
      }}

      />

      <mesh 
      ref = {devWorkAnimRef}
      geometry={nodes.DeskHitBoxAnim.geometry} 
      material={whiteMaterial} 
      position={[2.243, 1.947, -2.128]} 
      scale={[0, 0, 0]} 
      />
    </group>
  )
}

useGLTF.preload('/models/DeskHitbox.glb')
